
CREATE TABLE BUDGET
(
  BUDGET_SEQ  INT      NOT NULL AUTO_INCREMENT COMMENT '가계부 SEQ PK',
  BUDGET_NAME VARCHAR  NOT NULL COMMENT '가계부 명',
  DESCRIPTION TEXT     NULL     COMMENT '가계부 설명 및 비고 ',
  OWNER       INT      NOT NULL COMMENT '가계부 소유자',
  IS_PUBLIC   CHAR     NULL     DEFAULT 'N' COMMENT '가계부 공개 여부 Y, N CHAR(1)',
  CREATE_DT   DATETIME NULL     DEFAULT SYSDATE COMMENT '가계부 생성일시',
  PRIMARY KEY (BUDGET_SEQ)
) COMMENT '가계부에 대한 메타데이터 테이블';

CREATE TABLE BUDGET_CATEGORY
(
  CATEGORY_SEQ  INT      NOT NULL AUTO_INCREMENT COMMENT '가계부 카테고리 SEQ PK',
  BUDGET_SEQ    INT      NOT NULL COMMENT '가계부 SEQ PK',
  CATEGORY_NAME VARCHAR  NULL     COMMENT '카테고리 이름',
  IMAGE         VARCHAR  NULL     COMMENT '카테고리 이미지',
  CREATE_ID     VARCHAR  NULL     COMMENT '등록자',
  CREATE_DT     DATETIME NULL     COMMENT '등록일시',
  UPDATE_ID     VARCHAR  NULL     COMMENT '수정자',
  UPDATE_DT     DATETIME NULL     COMMENT '수정일시',
  PRIMARY KEY (CATEGORY_SEQ)
) COMMENT '가계부 데이터를 작성할 때 사용하는 카테고리';

CREATE TABLE BUDGET_DATA
(
  DATA_SEQ    INt      NOT NULL AUTO_INCREMENT COMMENT '가계부 데이터 SEQ PK',
  BUDGET_SEQ  INT      NOT NULL COMMENT '가계부 SEQ PK',
  CATEGORY_CD INT      NOT NULL COMMENT '가계부 카테고리 SEQ PK',
  AMOUNT      INT      NULL     COMMENT '금액',
  COUNT       INT      NULL     COMMENT '갯수',
  TOTAL       INT      NULL     COMMENT '전체 (금액 * 갯수)',
  TYPE        VARCHAR  NULL     COMMENT 'INCOME / OUTCOME',
  USE_DT      DATETIME NULL     DEFAULT SYSDATE COMMENT '사용일시',
  CREATE_ID   VARCHAR  NULL     COMMENT '등록자',
  CREATE_DT   DATETIME NULL     COMMENT '등록일시',
  UPDATE_ID   VARCHAR  NULL     COMMENT '수정자',
  UPDATE_DT   DATETIME NULL     COMMENT '수정일시',
  PRIMARY KEY (DATA_SEQ)
) COMMENT '가계부에 실제 데이터, ';

CREATE TABLE BUDGET_MEMBER
(
  BUDGET_MEMBER_SEQ INT      NOT NULL AUTO_INCREMENT COMMENT '가계부 멤버 SEQ PK',
  BUDGET_SEQ        INT      NOT NULL COMMENT '가계부 SEQ PK',
  USER_SEQ          INT      NOT NULL COMMENT '사용자 SEQ PK',
  BUDGET_ROLE       VARCHAR  NULL     COMMENT '가계부에 대한 권한',
  JOINED_DT         DATETIME NULL     COMMENT '가계부 참여일',
  STATUS            VARCHAR  NULL     COMMENT '상태값( ACTIVE, IN-ACTIVE)',
  PRIMARY KEY (BUDGET_MEMBER_SEQ)
) COMMENT '가계부를 작성할 수 있는 사용자 목록';

CREATE TABLE USER_AUTH
(
  USER_SEQ  INT      NOT NULL AUTO_INCREMENT COMMENT '사용자 SEQ PK',
  LOGIN_ID  VARCHAR  NOT NULL COMMENT '사용자 로그인 ID',
  PASSWORD  VARCHAR  NULL     COMMENT '사용자 패스워드',
  STATUS    VARCHAR  NULL     COMMENT '계정 상태',
  CREATE_DT DATETIME NULL     DEFAULT SYSDATE COMMENT '생성일시',
  UPDATE_DT DATETIME NULL     DEFAULT SYSDATE COMMENT '수정일시',
  PRIMARY KEY (USER_SEQ)
) COMMENT '사용자 로그인 및 권한 테이블';

ALTER TABLE USER_AUTH
  ADD CONSTRAINT UQ_LOGIN_ID UNIQUE (LOGIN_ID);

CREATE TABLE USER_INFO
(
  USER_SEQ  INT     NOT NULL COMMENT 'SEQ PK',
  USER_NAME VARCHAR NULL     COMMENT '사용자 이름',
  NICKNAME  VARCHAR NULL     COMMENT '사용자 닉네임',
  TELNO     VARCHAR NULL     COMMENT '핸드폰번호',
  EMAIL     VARCHAR NULL     COMMENT '이메일'
) COMMENT '사용자의 상세정보';

ALTER TABLE BUDGET_DATA
  ADD CONSTRAINT FK_BUDGET_TO_BUDGET_DATA
    FOREIGN KEY (BUDGET_SEQ)
    REFERENCES BUDGET (BUDGET_SEQ);

ALTER TABLE USER_INFO
  ADD CONSTRAINT FK_USER_AUTH_TO_USER_INFO
    FOREIGN KEY (USER_SEQ)
    REFERENCES USER_AUTH (USER_SEQ);

ALTER TABLE BUDGET_MEMBER
  ADD CONSTRAINT FK_BUDGET_TO_BUDGET_MEMBER
    FOREIGN KEY (BUDGET_SEQ)
    REFERENCES BUDGET (BUDGET_SEQ);

ALTER TABLE BUDGET
  ADD CONSTRAINT FK_USER_AUTH_TO_BUDGET
    FOREIGN KEY (OWNER)
    REFERENCES USER_AUTH (USER_SEQ);

ALTER TABLE BUDGET_MEMBER
  ADD CONSTRAINT FK_USER_AUTH_TO_BUDGET_MEMBER
    FOREIGN KEY (USER_SEQ)
    REFERENCES USER_AUTH (USER_SEQ);

ALTER TABLE BUDGET_CATEGORY
  ADD CONSTRAINT FK_BUDGET_TO_BUDGET_CATEGORY
    FOREIGN KEY (BUDGET_SEQ)
    REFERENCES BUDGET (BUDGET_SEQ);

ALTER TABLE BUDGET_DATA
  ADD CONSTRAINT FK_BUDGET_CATEGORY_TO_BUDGET_DATA
    FOREIGN KEY (CATEGORY_CD)
    REFERENCES BUDGET_CATEGORY (CATEGORY_SEQ);

CREATE INDEX PK_USER_AUTH
  ON USER_AUTH (USER_SEQ ASC);

